package com.vsca.vsnapvoicecollege.Repository


object ApiRequestNames {
    var DeviceType = "android"
    const val Req_id = "id"
    const val Req_AppId = "AppId"
    const val Req_VersionID = "versionID"
    const val Req_DeviceType = "device_type"
    const val Req_msgtype = "msgtype"
    const val Req_mobileNumber = "mobilenumber"
    const val Req_password = "Password"
    const val Req_collegeid = "collegeid"
    const val Req_detailsid = "detailsid"
    const val Req_userid = "userid"
    const val Req_priority = "priority"
    const val Req_countryid = "countryid"
    const val Req_langid = "langid"
    const val Req_MemberID = "member_id"
    const val Req_college_id = "college_id"
    const val Req_user_id = "user_id"
    const val Req_dept_id = "dept_id"
    const val Req_sem_id = "sem_id"
    const val Req_section_id = "section_id"
    const val Req_colgid = "colgid"
    const val Req_i_course_id = "i_course_id"
    const val Req_i_sem_id = "i_semester_id"
    const val Req_i_student_id = "i_student_id"
    const val Req_i_category_id = "i_category_id"
    const val Req_appid = "appid"
    const val Req_type = "type"
    const val Req_sectionid = "sectionid"
    const val Req_readtype = "readtype"
    const val Req_semesterid = "semesterid"
    const val Req_menuid = "menuid"
    const val Req_departmentid = "departmentid"
    const val Req_studentid = "studentid"
    const val Req_examheaderid = "examheaderid"
    const val Req_yearid = "yearid"
    const val Req_Attendancedate = "attendancedate"
    const val Req_staffid = "staffid"
    const val Req_filetype = "filetype"
    const val Req_oldpassword = "oldpassword"
    const val Req_newpassword = "newpassword"
    const val Req_student_id = "student_id"
    const val Req_mobileno = "mobile_no"
    const val Req_devicetoken = "devicetoken"
    const val Req_devicetype = "devicetype"
    const val Req_ad_device_token = "device_token"
    const val Req_previous_add_id = "previous_add_id"
    const val Req_div_id = "div_id"
    const val Req_Callertye = "callertype"
    const val Req_MessageContent = "messagecontent"
    const val Req_Description = "description"
    const val Req_isStudent = "isstudent"
    const val Req_isStaff = "isstaff"
    const val Req_isParent = "isparent"
}
